# Generated by Django 5.1.15 on 2026-09-09 05:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_accounts', '0017_seed_missing_analytics_platform_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaDataDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('instagram_login', 'Instagram (Direct)'), ('linkedin_personal', 'LinkedIn (Personal Profile)'), ('linkedin_company', 'LinkedIn (Company Page)'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('threads', 'Threads'), ('bluesky', 'Bluesky'), ('google_business', 'Google Business Profile'), ('mastodon', 'Mastodon'), ('devto', 'DEV.to')], max_length=30)),
                ('platform_user_id', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('nothing_to_delete', 'Nothing to delete'), ('failed', 'Failed')], max_length=20)),
                ('accounts_deleted', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_accounts_meta_data_deletion_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='socialaccount',
            name='platform_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='App-scoped ID of the user who authorized the connection.', max_length=255),
        ),
    ]
